"""api key hash sha256 unique

Revision ID: d1ac4efa124f
Revises: 3f7122a28be3
Create Date: 2026-09-23 20:49:54.372998

说明：本迁移由 Alembic 生成，字段含义见 docs/PRD.md 附录 A。
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1ac4efa124f'
down_revision: Union[str, None] = '3f7122a28be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_api_key', 'api_key_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               type_=sa.String(length=64),
               comment='sha256(明文) 的十六进制摘要',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_sys_api_key_api_key_hash'), 'sys_api_key', ['api_key_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sys_api_key_api_key_hash'), 'sys_api_key', type_='unique')
    op.alter_column('sys_api_key', 'api_key_hash',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='sha256(明文) 的十六进制摘要',
               existing_nullable=False)
    # ### end Alembic commands ###

