"""event cheat label

Revision ID: ea80dfdd5cfb
Revises: d1ac4efa124f
Create Date: 2026-09-24 12:58:59.599599

说明：本迁移由 Alembic 生成，字段含义见 docs/PRD.md 附录 A。

rc_event.is_cheat 是**离线训练的监督标签**（docs/PRD.md §8.3 第 1 步"场景标签"）：
1 = 由作弊场景脚本产生的事件，0 = 正常账号事件，NULL = 线上真实事件。
为什么放在事件表而不是单独建标签表：标签是"这条事件是由什么账号产生的"这一属性，
与事件一一对应；单独建表会让"样本 = 事件 × 快照 × 标签"的三表连接在多一层 JOIN
的同时失去 NOT NULL 之外的完整性保证，而本字段的使用者只有一个（训练脚本）。
**线上事件永远为 NULL**，因此训练脚本必须显式过滤 `is_cheat IS NOT NULL`，
不会把真实流量误当作负样本。
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ea80dfdd5cfb'
down_revision: Union[str, None] = 'd1ac4efa124f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rc_event', sa.Column('is_cheat', sa.Boolean(), nullable=True, comment='离线训练标签：1=作弊账号产生，0=正常账号产生，NULL=线上真实事件（不参与训练）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rc_event', 'is_cheat')
    # ### end Alembic commands ###
