"""init p0 schema

Revision ID: e62c7b4dd2ad
Revises: 
Create Date: 2026-09-23 20:44:33.438102

说明：本迁移由 Alembic 生成，字段含义见 docs/PRD.md 附录 A。
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e62c7b4dd2ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_coupon_receive',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('receive_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('coupon_id', sa.String(length=32), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='券面额'),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_coupon_receive')),
    sa.UniqueConstraint('receive_no', name=op.f('uq_biz_coupon_receive_receive_no')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_biz_coupon_receive_user_id'), 'biz_coupon_receive', ['user_id'], unique=False)
    op.create_table('biz_customer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.Column('register_channel', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_customer')),
    sa.UniqueConstraint('user_id', name=op.f('uq_biz_customer_user_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_biz_customer_phone'), 'biz_customer', ['phone'], unique=False)
    op.create_table('biz_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('address_hash', sa.String(length=64), nullable=True, comment='收货地址指纹，用于聚集度特征'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_order')),
    sa.UniqueConstraint('order_no', name=op.f('uq_biz_order_order_no')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_biz_order_address_hash'), 'biz_order', ['address_hash'], unique=False)
    op.create_index(op.f('ix_biz_order_user_id'), 'biz_order', ['user_id'], unique=False)
    op.create_table('biz_product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_product')),
    sa.UniqueConstraint('product_id', name=op.f('uq_biz_product_product_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('biz_refund',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('refund_no', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True, comment='如：未收到货 / 质量问题'),
    sa.Column('apply_type', sa.String(length=16), nullable=True, comment='refund_only / return_refund'),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_refund')),
    sa.UniqueConstraint('refund_no', name=op.f('uq_biz_refund_refund_no')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_biz_refund_order_no'), 'biz_refund', ['order_no'], unique=False)
    op.create_index(op.f('ix_biz_refund_user_id'), 'biz_refund', ['user_id'], unique=False)
    op.create_table('rc_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增即链序'),
    sa.Column('actor_id', sa.String(length=64), nullable=True, comment='操作者账号；系统动作为 system'),
    sa.Column('actor_name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False, comment='login/case_claim/case_dispose/rule_update/...'),
    sa.Column('target_type', sa.String(length=32), nullable=True, comment='case/rule/list/model/config'),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('before_json', sa.Text(), nullable=True, comment='变更前（规范化 JSON 字符串）'),
    sa.Column('after_json', sa.Text(), nullable=True, comment='变更后（规范化 JSON 字符串）'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='人工填写的处置/变更原因'),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_audit_log')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('rc_decision',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=48), nullable=False, comment='对外暴露的决策编号'),
    sa.Column('event_id', sa.String(length=48), nullable=False),
    sa.Column('rule_score', sa.Integer(), nullable=False),
    sa.Column('model_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('action_hint', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=16), nullable=False),
    sa.Column('fusion_alpha', sa.Numeric(precision=4, scale=3), nullable=False, comment='本次使用的融合权重，便于复算'),
    sa.Column('fusion_mode', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=16), nullable=True),
    sa.Column('case_no', sa.String(length=32), nullable=True, comment='若生成/合并了案件'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='命中规则条数'),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), nullable=False, comment='是否幂等缓存命中'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_decision')),
    sa.UniqueConstraint('decision_id', name=op.f('uq_rc_decision_decision_id')),
    sa.UniqueConstraint('event_id', name=op.f('uq_rc_decision_event_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_decision_action_time', 'rc_decision', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_rc_decision_case_no'), 'rc_decision', ['case_no'], unique=False)
    op.create_index('ix_rc_decision_created', 'rc_decision', ['created_at'], unique=False)
    op.create_index('ix_rc_decision_level_time', 'rc_decision', ['risk_level', 'created_at'], unique=False)
    op.create_table('rc_decision_hit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=48), nullable=False),
    sa.Column('rule_code', sa.String(length=32), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('rule_category', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False, comment='该规则本次贡献的分值'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='可读的触发原因，如「同设备 24h 关联 7 个账号」'),
    sa.Column('evidence', sa.JSON(), nullable=True, comment='逐条件求值结果，供证据链展示'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_decision_hit')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_decision_hit_rule_time', 'rc_decision_hit', ['rule_code', 'created_at'], unique=False)
    op.create_table('rc_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=48), nullable=False, comment='业务方生成，幂等键'),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('device_fingerprint', sa.JSON(), nullable=True, comment='os/机型/分辨率/App 版本等'),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ip_region', sa.String(length=64), nullable=True),
    sa.Column('address_hash', sa.String(length=64), nullable=True),
    sa.Column('biz_no', sa.String(length=32), nullable=True, comment='关联业务单据号（订单号/退款单号/券记录号）'),
    sa.Column('occurred_at', sa.DateTime(), nullable=False, comment='业务发生时间（UTC）'),
    sa.Column('received_at', sa.DateTime(), nullable=False, comment='风控接收时间（UTC）'),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False, comment='事件类型专有字段原样留存，保证可回放'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='接入到响应的耗时；异步回填'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_event')),
    sa.UniqueConstraint('event_id', name=op.f('uq_rc_event_event_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_event_device_time', 'rc_event', ['device_id', 'occurred_at'], unique=False)
    op.create_index('ix_rc_event_ip_time', 'rc_event', ['ip', 'occurred_at'], unique=False)
    op.create_index('ix_rc_event_type_time', 'rc_event', ['event_type', 'occurred_at'], unique=False)
    op.create_index('ix_rc_event_user_time', 'rc_event', ['user_id', 'occurred_at'], unique=False)
    op.create_table('rc_feature_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=48), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False, comment='扁平键值：{feature_key_window: value}'),
    sa.Column('window_profile', sa.String(length=32), nullable=False),
    sa.Column('calc_cost_ms', sa.Integer(), nullable=True, comment='特征计算耗时，用于性能预算核算'),
    sa.Column('feature_version', sa.String(length=16), nullable=False, comment='特征定义版本，保证历史可复现'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_feature_snapshot')),
    sa.UniqueConstraint('event_id', name=op.f('uq_rc_feature_snapshot_event_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('rc_list_entry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('list_type', sa.String(length=8), nullable=False, comment='black/white/gray'),
    sa.Column('dimension', sa.String(length=16), nullable=False, comment='user/phone/ip/device/address'),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='数值越小优先级越高'),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='为空表示永久有效'),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_list_entry')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_list_dim_value', 'rc_list_entry', ['dimension', 'value'], unique=False)
    op.create_index('uq_rc_list_type_dim_value', 'rc_list_entry', ['list_type', 'dimension', 'value'], unique=True)
    op.create_table('rc_model_contribution',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=48), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('feature_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('contribution', sa.Numeric(precision=12, scale=6), nullable=False, comment='w_i * z_i'),
    sa.Column('direction', sa.String(length=8), nullable=False, comment='up/down'),
    sa.Column('rank_no', sa.Integer(), nullable=False, comment='1 = 影响最大'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_model_contribution')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_rc_model_contribution_decision_id'), 'rc_model_contribution', ['decision_id'], unique=False)
    op.create_table('rc_model_version',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False, comment='特征顺序，推理时严格按此顺序取数'),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='auc/ks/precision_at_100/samples'),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False, comment='同一时刻仅允许一个启用版本'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_model_version')),
    sa.UniqueConstraint('version', name=op.f('uq_rc_model_version_version')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('rc_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='规则编码，如 RC_ENV_001'),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scene', sa.String(length=32), nullable=False, comment='适用场景：coupon/order/after_sale/login/all'),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False, comment='AST，唯一真源'),
    sa.Column('condition_text', sa.Text(), nullable=False, comment='表达式的文本形态，便于阅读与编辑'),
    sa.Column('score', sa.Integer(), nullable=False, comment='命中后累加的分值'),
    sa.Column('action_hint', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='数值越小越先求值'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_rule')),
    sa.UniqueConstraint('code', name=op.f('uq_rc_rule_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_rule_scene_enabled', 'rc_rule', ['scene', 'enabled'], unique=False)
    op.create_table('rc_rule_version',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_code', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('action_hint', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False, comment='create/update/toggle/rollback'),
    sa.Column('changed_by', sa.String(length=64), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_rule_version')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_rc_rule_version_rule_code'), 'rc_rule_version', ['rule_code'], unique=False)
    op.create_table('sys_api_key',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='调用方名称，如「模拟业务端」'),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最近一次调用时间，便于识别僵尸密钥'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_api_key')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=64), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False, comment='统一按字符串存储，读取方自行转型'),
    sa.Column('value_type', sa.String(length=16), nullable=False, comment='str/int/float/bool/json'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_config')),
    sa.UniqueConstraint('config_key', name=op.f('uq_sys_config_config_key')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录名'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='bcrypt 摘要'),
    sa.Column('real_name', sa.String(length=64), nullable=True, comment='展示名'),
    sa.Column('role', sa.String(length=32), nullable=False, comment='auditor/strategist/admin'),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user')),
    sa.UniqueConstraint('username', name=op.f('uq_sys_user_username')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user')
    op.drop_table('sys_config')
    op.drop_table('sys_api_key')
    op.drop_index(op.f('ix_rc_rule_version_rule_code'), table_name='rc_rule_version')
    op.drop_table('rc_rule_version')
    op.drop_index('ix_rc_rule_scene_enabled', table_name='rc_rule')
    op.drop_table('rc_rule')
    op.drop_table('rc_model_version')
    op.drop_index(op.f('ix_rc_model_contribution_decision_id'), table_name='rc_model_contribution')
    op.drop_table('rc_model_contribution')
    op.drop_index('uq_rc_list_type_dim_value', table_name='rc_list_entry')
    op.drop_index('ix_rc_list_dim_value', table_name='rc_list_entry')
    op.drop_table('rc_list_entry')
    op.drop_table('rc_feature_snapshot')
    op.drop_index('ix_rc_event_user_time', table_name='rc_event')
    op.drop_index('ix_rc_event_type_time', table_name='rc_event')
    op.drop_index('ix_rc_event_ip_time', table_name='rc_event')
    op.drop_index('ix_rc_event_device_time', table_name='rc_event')
    op.drop_table('rc_event')
    op.drop_index('ix_rc_decision_hit_rule_time', table_name='rc_decision_hit')
    op.drop_table('rc_decision_hit')
    op.drop_index('ix_rc_decision_level_time', table_name='rc_decision')
    op.drop_index('ix_rc_decision_created', table_name='rc_decision')
    op.drop_index(op.f('ix_rc_decision_case_no'), table_name='rc_decision')
    op.drop_index('ix_rc_decision_action_time', table_name='rc_decision')
    op.drop_table('rc_decision')
    op.drop_table('rc_audit_log')
    op.drop_index(op.f('ix_biz_refund_user_id'), table_name='biz_refund')
    op.drop_index(op.f('ix_biz_refund_order_no'), table_name='biz_refund')
    op.drop_table('biz_refund')
    op.drop_table('biz_product')
    op.drop_index(op.f('ix_biz_order_user_id'), table_name='biz_order')
    op.drop_index(op.f('ix_biz_order_address_hash'), table_name='biz_order')
    op.drop_table('biz_order')
    op.drop_index(op.f('ix_biz_customer_phone'), table_name='biz_customer')
    op.drop_table('biz_customer')
    op.drop_index(op.f('ix_biz_coupon_receive_user_id'), table_name='biz_coupon_receive')
    op.drop_table('biz_coupon_receive')
    # ### end Alembic commands ###

