"""p1 case tables

Revision ID: 7e9dc8ec3f41
Revises: ea80dfdd5cfb
Create Date: 2026-09-24 19:50:05.422436

说明：本迁移由 Alembic 生成，字段含义见 docs/PRD.md 附录 A 与 docs/ARCHITECTURE.md §6.3。

P1 案件域四张表（docs/PRD.md §9）。三处需要解释的取舍：

1. **纯新增、无破坏性变更**：不触碰任何 P0 表。`rc_decision.case_no` 列在 P0
   就已建好（当时恒为 NULL，只留格式与调用点），因此 P1 不需要给决策表加字段，
   历史决策的 `case_no` 保持 NULL —— 它表示"那条决策发生在案件功能上线之前"，
   与"属于某案件但没记上"是两件事，用 NULL 表达前者是准确的。
2. **不做物理外键**：与 P0 的表风格一致（`rc_decision.event_id` 等也无外键）。
   理由是案件表要承受决策热路径的写入，`ON DELETE/UPDATE` 的级联语义在
   "演示系统会直接改库造数据"的场景下反而变成障碍；完整性由服务层保证。
3. **`rc_case_event` 的唯一键是 (case_no, event_id) 而不是 event_id**：
   同一事件理论上只属于一个案件（合案键含场景，跨场景事件不会合到一起），
   但**不过滤成全局唯一**是刻意的 —— 如果哪天出现"同一事件跨场景被两次建案"
   的异常，唯一键会直接拒绝写入并把问题暴露在日志里，而不是静默丢掉第二笔关联。
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7e9dc8ec3f41'
down_revision: Union[str, None] = 'ea80dfdd5cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rc_case',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_no', sa.String(length=32), nullable=False, comment='案件编号，对外主键'),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_value', sa.String(length=64), nullable=False, comment='主体值（P1 为 user_id）'),
    sa.Column('scene', sa.String(length=32), nullable=False, comment='规则场景：login/coupon/order/after_sale'),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False, comment='案件内最高风险等级'),
    sa.Column('max_score', sa.Integer(), nullable=False, comment='案件内最高综合分'),
    sa.Column('hit_cnt', sa.Integer(), nullable=False, comment='累计命中规则条数'),
    sa.Column('event_cnt', sa.Integer(), nullable=False, comment='关联事件数'),
    sa.Column('first_at', sa.DateTime(), nullable=False, comment='首次触发时间'),
    sa.Column('last_at', sa.DateTime(), nullable=False, comment='末次触发时间，合案窗口以它为准'),
    sa.Column('last_event_id', sa.String(length=48), nullable=True, comment='最近一次关联事件，详情页默认展开它'),
    sa.Column('last_decision_id', sa.String(length=48), nullable=True),
    sa.Column('handler', sa.String(length=64), nullable=True, comment='当前处理人用户名，未接手为空'),
    sa.Column('handler_id', sa.BigInteger(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('disposed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_reason', sa.String(length=255), nullable=True),
    sa.Column('dispose_result', sa.String(length=16), nullable=True, comment='冗余的最终业务结论：approve/reject'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_case')),
    sa.UniqueConstraint('case_no', name=op.f('uq_rc_case_case_no')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_case_handler_status', 'rc_case', ['handler_id', 'status'], unique=False)
    op.create_index('ix_rc_case_scene_status', 'rc_case', ['scene', 'status', 'last_at'], unique=False)
    op.create_index('ix_rc_case_status_time', 'rc_case', ['status', 'last_at'], unique=False)
    op.create_index('ix_rc_case_subject_status', 'rc_case', ['subject_type', 'subject_value', 'scene', 'status', 'last_at'], unique=False)
    op.create_table('rc_case_action',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_no', sa.String(length=32), nullable=False),
    sa.Column('business_result', sa.String(length=16), nullable=False, comment='approve/reject'),
    sa.Column('risk_actions', sa.JSON(), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=False, comment='处置原因备注（≥10 字）'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_name', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('status_before', sa.String(length=16), nullable=False),
    sa.Column('status_after', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_case_action')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_case_action_case_time', 'rc_case_action', ['case_no', 'created_at'], unique=False)
    op.create_table('rc_case_action_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.BigInteger(), nullable=False),
    sa.Column('case_no', sa.String(length=32), nullable=False),
    sa.Column('risk_action', sa.String(length=32), nullable=False),
    sa.Column('exec_result', sa.String(length=16), nullable=False, comment='success/failed/skipped'),
    sa.Column('target_type', sa.String(length=32), nullable=True, comment='order/refund/customer/list_entry'),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True, comment='联动明细/失败原因，前端直接展示'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_case_action_item')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_case_action_item_action', 'rc_case_action_item', ['action_id'], unique=False)
    op.create_index('ix_rc_case_action_item_case', 'rc_case_action_item', ['case_no'], unique=False)
    op.create_table('rc_case_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_no', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=48), nullable=False),
    sa.Column('decision_id', sa.String(length=48), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('scene', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='该事件的规则命中条数'),
    sa.Column('biz_no', sa.String(length=32), nullable=True, comment='关联业务单据号，处置联动按它定位订单/退款单'),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rc_case_event')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rc_case_event_case_time', 'rc_case_event', ['case_no', 'occurred_at'], unique=False)
    op.create_index('ix_rc_case_event_event', 'rc_case_event', ['event_id'], unique=False)
    op.create_index('uq_rc_case_event_case_event', 'rc_case_event', ['case_no', 'event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rc_case_event_case_event', table_name='rc_case_event')
    op.drop_index('ix_rc_case_event_event', table_name='rc_case_event')
    op.drop_index('ix_rc_case_event_case_time', table_name='rc_case_event')
    op.drop_table('rc_case_event')
    op.drop_index('ix_rc_case_action_item_case', table_name='rc_case_action_item')
    op.drop_index('ix_rc_case_action_item_action', table_name='rc_case_action_item')
    op.drop_table('rc_case_action_item')
    op.drop_index('ix_rc_case_action_case_time', table_name='rc_case_action')
    op.drop_table('rc_case_action')
    op.drop_index('ix_rc_case_subject_status', table_name='rc_case')
    op.drop_index('ix_rc_case_status_time', table_name='rc_case')
    op.drop_index('ix_rc_case_scene_status', table_name='rc_case')
    op.drop_index('ix_rc_case_handler_status', table_name='rc_case')
    op.drop_table('rc_case')
    # ### end Alembic commands ###
